import pytest
from unittest.mock import MagicMock
from sqlmodel import Session
from backend.src.models.user import User
from backend.src.models.personalization import PersonalizationData
from backend.src.services.user_service import UserService
from backend.src.utils.security import get_password_hash, verify_password
from backend.src.utils.errors import UserAlreadyExistsException, InvalidCredentialsException

# Mock for get_password_hash and verify_password
# In a real scenario, you'd mock these from the security module,
# but for unit testing the service, we can directly control their behavior.
def mock_get_password_hash(password: str) -> str:
    return f"hashed_{password}"

def mock_verify_password(plain_password: str, hashed_password: str) -> bool:
    return hashed_password == f"hashed_{plain_password}"

@pytest.fixture
def mock_session():
    return MagicMock(spec=Session)

@pytest.fixture
def user_service(mock_session):
    return UserService(session=mock_session)

def test_get_user_by_email_exists(mock_session, user_service):
    # Setup
    test_user = User(id=1, email="test@example.com", password_hash="hashed_password")
    mock_session.exec.return_value.first.return_value = test_user

    # Execute
    user = user_service.get_user_by_email("test@example.com")

    # Assert
    assert user == test_user
    mock_session.exec.assert_called_once()

def test_get_user_by_email_not_exists(mock_session, user_service):
    # Setup
    mock_session.exec.return_value.first.return_value = None

    # Execute
    user = user_service.get_user_by_email("nonexistent@example.com")

    # Assert
    assert user is None
    mock_session.exec.assert_called_once()

def test_create_user_with_password_success(mock_session, user_service, monkeypatch):
    # Setup
    monkeypatch.setattr("backend.src.services.user_service.get_password_hash", mock_get_password_hash)
    mock_session.exec.return_value.first.return_value = None # User does not exist

    # Execute
    user = user_service.create_user_with_password(
        email="new@example.com",
        password="password123",
        software_background=["Python"],
        hardware_background=["Raspberry Pi"]
    )

    # Assert
    assert user.email == "new@example.com"
    assert user.password_hash == "hashed_password123"
    mock_session.add.assert_called()
    mock_session.commit.assert_called()
    mock_session.refresh.assert_called()
    # Check if PersonalizationData was added
    mock_session.add.assert_any_call(
        pytest.approx(PersonalizationData(user_id=user.id, software_background=["Python"], hardware_background=["Raspberry Pi"]), abs=1e-6) # Compare only the values, ignore the id generated by db
    )

def test_create_user_with_password_already_exists(mock_session, user_service):
    # Setup
    test_user = User(id=1, email="test@example.com", password_hash="hashed_password")
    mock_session.exec.return_value.first.return_value = test_user

    # Execute & Assert
    with pytest.raises(UserAlreadyExistsException):
        user_service.create_user_with_password("test@example.com", "password123")

def test_create_user_with_oauth_success(mock_session, user_service):
    # Setup
    mock_session.exec.return_value.first.return_value = None # User does not exist
    oauth_ids = {"google": "google_id_123"}

    # Execute
    user = user_service.create_user_with_oauth(
        email="oauth@example.com",
        oauth_provider_ids=oauth_ids
    )

    # Assert
    assert user.email == "oauth@example.com"
    assert user.oauth_provider_ids == oauth_ids
    mock_session.add.assert_called()
    mock_session.commit.assert_called()
    mock_session.refresh.assert_called()

def test_authenticate_user_success(mock_session, user_service, monkeypatch):
    # Setup
    monkeypatch.setattr("backend.src.services.user_service.verify_password", mock_verify_password)
    test_user = User(id=1, email="test@example.com", password_hash="hashed_password123")
    mock_session.exec.return_value.first.return_value = test_user

    # Execute
    user = user_service.authenticate_user("test@example.com", "password123")

    # Assert
    assert user == test_user

def test_authenticate_user_invalid_password(mock_session, user_service, monkeypatch):
    # Setup
    monkeypatch.setattr("backend.src.services.user_service.verify_password", mock_verify_password)
    test_user = User(id=1, email="test@example.com", password_hash="hashed_wrong_password")
    mock_session.exec.return_value.first.return_value = test_user

    # Execute
    user = user_service.authenticate_user("test@example.com", "password123")

    # Assert
    assert user is None

def test_authenticate_user_not_found(mock_session, user_service):
    # Setup
    mock_session.exec.return_value.first.return_value = None

    # Execute
    user = user_service.authenticate_user("nonexistent@example.com", "password123")

    # Assert
    assert user is None
