openapi: 3.0.0
info:
  title: User Authentication and Profile API
  version: 1.0.0
  description: API for user registration, login, session management, and personalized profile data.

servers:
  - url: /api/v1
    description: Base URL for API endpoints

components:
  schemas:
    UserRegistration:
      type: object
      required:
        - email
        - password
        - software_background
        - hardware_background
      properties:
        email:
          type: string
          format: email
          description: User's unique email address.
        password:
          type: string
          format: password
          description: User's password (min 8 chars, 1 uppercase, 1 lowercase, 1 number).
        software_background:
          type: array
          items:
            type: string
          description: List of user's software background (predefined categories + optional free text).
        hardware_background:
          type: array
          items:
            type: string
          description: List of user's hardware background (predefined categories + optional free text).

    UserLogin:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: User's email address.
        password:
          type: string
          format: password
          description: User's password.

    UserOAuthLogin:
      type: object
      required:
        - provider
        - token
      properties:
        provider:
          type: string
          enum: [google, github]
          description: OAuth provider (e.g., 'google', 'github').
        token:
          type: string
          description: OAuth access token received from the provider.

    UserProfile:
      type: object
      properties:
        id:
          type: string
          description: Unique user ID.
        email:
          type: string
          format: email
          description: User's email address.
        software_background:
          type: array
          items:
            type: string
          description: List of user's software background.
        hardware_background:
          type: array
          items:
            type: string
          description: List of user's hardware background.

    PersonalizationData:
      type: object
      properties:
        software_preferences:
          type: array
          items:
            type: string
          description: Detailed software preferences for personalization.
        hardware_preferences:
          type: array
          items:
            type: string
          description: Detailed hardware preferences for personalization.

    AuthResponse:
      type: object
      properties:
        message:
          type: string
        user_id:
          type: string
        session_token:
          type: string
          description: JWT or opaque token for maintaining session state.
        user_profile:
          $ref: '#/components/schemas/UserProfile'

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string

security:
  - bearerAuth: []

paths:
  /signup:
    post:
      summary: Register a new user with email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: User successfully registered.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Invalid input or email already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /signup/oauth:
    post:
      summary: Register or login a user via OAuth provider (Google/GitHub).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserOAuthLogin'
      responses:
        '200':
          description: User successfully registered or logged in via OAuth.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Invalid OAuth token or provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /login:
    post:
      summary: Authenticate a user with email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: User successfully logged in.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /logout:
    post:
      summary: Invalidate the current user session.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User successfully logged out.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Unauthorized, no active session.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /user/profile:
    get:
      summary: Get the profile of the authenticated user.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Unauthorized, invalid or missing session token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /user/personalization-data:
    get:
      summary: Retrieve personalization data for the authenticated user.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Personalization data retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalizationData'
        '401':
          description: Unauthorized, invalid or missing session token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
